version: '3.8'

services:

  postgres:
    image: postgres:14.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret

  backend:
    depends_on:
      - postgres
    image: node:lts
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 3001:3001
      - 5555:5555
    stdin_open: true
    restart: always
    command:  sh -c "npm install
              && npx prisma migrate dev
              && npm run start:dev"

  frontend:
    image: node:lts
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - 3000:3000
    command:  sh -c "npm install
              && npm start"

volumes:
  postgres-data: