version: '3.8'

services:

  server:
    image: node:17.5
    command: sh -c "npm install"
    ports:
      - 3000:3000
    working_dir: /server
    volumes:
      - ./:/server
    environment:
  
  database:
    image: postgres:14.2
    volumes:
    environment:

volumes:
