version: '3.8'

services:

  backend:
    image: node:17.5
    command:  sh -c "npm install
              && npx prisma migrate dev
              && npm run start:dev"
    ports:
      - 3001:3001
    stdin_open: true
    working_dir: /backend
    volumes:
      - ./backend:/backend
  
  frontend:
    image: node:17.5
    command:  sh -c "npm install
              && npm start"
    ports:
      - 3000:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: