version: '3.8'

services:

  serv:
    image: node:17.5
    command:  sh -c "npm install
              && npm run start:dev"
    ports:
      - 3001:3001
    working_dir: /serv
    volumes:
      - ./pong:/serv
    # environment:
  
#   db:
#     image: postgres:14.2
#     environment:
#       - POSTGRES_PASSWORD=secret
#       - PGUSER=secret

#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data: